### ISSUE TITLE
错误日志

### ISSUE THREAD

**Issue by vsxen** [djyde/cown#6]
sudo npm install cown -g
cown -v
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/.cown_npminstall/node_modules/.0.1.1@cown/db.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.read (/usr/local/lib/node_modules/.cown_npminstall/node_modules/.0.12.5@lowdb/file-sync.js:29:10)
    at Function.db.read (/usr/local/lib/node_modules/.cown_npminstall/node_modules/.0.12.5@lowdb/index.js:55:31)
    at low (/usr/local/lib/node_modules/.cown_npminstall/node_modules/.0.12.5@lowdb/index.js:136:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/.cown_npminstall/node_modules/.0.1.1@cown/lib/db.js:8:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
➜ qq@iMac  ~  node -v
v4.5.0
➜ qq@iMac  ~  npm -v
2.15.9

**Comment by djyde** [comment]
要 sudo ?

**Comment by vsxen** [comment]
用sudo就可以了
看动画好像不是sudo？可以修改吗？

新问题
➜ qq@iMac  ~  sudo cown use blog  
Buckets of qiniu:
-  blog
  
  blog2

➜ qq@iMac  ~  sudo cown upload /Users/qq/Desktop/sub.png 
No using bucket! Use `$ cown use <name>` to use a bucket.

**Comment by djyde** [comment]
用不用 sudo 取决于你的 node 运行环境。用 nvm 不需要 sudo, 如果是全局安装则需要

**Comment by vsxen** [comment]
新问题
➜ qq@iMac ~ sudo cown use blog

Buckets of qiniu:

blog

blog2

➜ qq@iMac ~ sudo cown upload /Users/qq/Desktop/sub.png 
No using bucket! Use $ cown use <name> to use a bucket.
无法上传

**Comment by djyde** [comment]
你还没 use 一个 bucket 吧

**Comment by vsxen** [comment]
上面 不是 有 `sudo cown use  blog`  吗
算了 可能此工具不适合吧  谢谢
